---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart mysql
  systemd:
    name: mariadb
    state: restarted

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted

...
